<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AvaloniaVersion>11.3.20</AvaloniaVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
